let config = {
  content: [
    {
      Category: "Starters",
      SubCategory: "Roll",
      DishName: "Chicken Roll",
      DishDescrip: "Chicken Roll",
      DishCost: "£10",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: false,
      spicelevel: 2,
    },
    {
      Category: "Starters",
      SubCategory: "Roll",
      DishName: "Egg Roll",
      DishDescrip: "Egg Roll",
      DishCost: "£11",
      URL: "./images/menuimg/002_EggRoll.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Roll",
      DishName: "Veg Roll",
      DishDescrip: "Veg Roll",
      DishCost: "£12",
      URL: "./images/menuimg/003_VegRoll.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Roll",
      DishName: "",
      DishDescrip: "",
      DishCost: "",
      URL: "",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Soup",
      DishName: "Lamb Soup",
      DishDescrip: "Lamb Soup",
      DishCost: "£13",
      URL: "./images/menuimg/004_LambSoup.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Soup",
      DishName: "Chicken Soup",
      DishDescrip: "Chicken Soup",
      DishCost: "£14",
      URL: "./images/menuimg/005_ChickenSoup.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Papadum",
      DishDescrip: "Papadum",
      DishCost: "£15",
      URL: "./images/menuimg/006_Papadum.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Medhu Vadai",
      DishDescrip: "Medhu Vadai",
      DishCost: "£10",
      URL: "./images/menuimg/007_MedhuVadai.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Masal Vadai",
      DishDescrip: "Masal Vadai",
      DishCost: "£11",
      URL: "./images/menuimg/008_MasalVadai.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Thair Vadai",
      DishDescrip: "Thair Vadai",
      DishCost: "£12",
      URL: "./images/menuimg/009_ThairVadai.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Panner 65",
      DishDescrip: "Panner 65",
      DishCost: "£13",
      URL: "./images/menuimg/010_Panner65.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Mashroom 65",
      DishDescrip: "Mashroom 65",
      DishCost: "£14",
      URL: "./images/menuimg/011_Mushroom65.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Gobi 65",
      DishDescrip: "Gobi 65",
      DishCost: "£15",
      URL: "./images/menuimg/012_Gobi65.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Gobi Manjurian",
      DishDescrip: "Gobi Manjurian",
      DishCost: "£10",
      URL: "./images/menuimg/013_Gobi Manjurian.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Panner Butter Masala",
      DishDescrip: "Panner Butter Masala",
      DishCost: "£11",
      URL: "./images/menuimg/014_Paneer Butter Masala.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Gobi Masala",
      DishDescrip: "Gobi Masala",
      DishCost: "£12",
      URL: "./images/menuimg/015_Gobi Masala.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Mashroom Masala",
      DishDescrip: "Mashroom Masala",
      DishCost: "£13",
      URL: "./images/menuimg/016_Mushroom Masala.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Fries",
      DishDescrip: "Fries",
      DishCost: "£14",
      URL: "./images/menuimg/017_Fries.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Onion Bhaji",
      DishDescrip: "Onion Bhaji",
      DishCost: "£15",
      URL: "./images/menuimg/018_Onion Bhaji.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Veg Starters",
      DishName: "Potato Bhaji",
      DishDescrip: "Potato Bhaji",
      DishCost: "£10",
      URL: "./images/menuimg/019_Potato Bhajji.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Grill Chicken Half",
      DishDescrip: "Grill Chicken Half",
      DishCost: "£11",
      URL: "./images/menuimg/020_Grill Chicken Half.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "BBQ Half",
      DishDescrip: "BBQ Half",
      DishCost: "£12",
      URL: "./images/menuimg/021_BBQ Half.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Tandoori Half / Quarter",
      DishDescrip: "Tandoori Half / Quarter",
      DishCost: "£13",
      URL: "./images/menuimg/022_Tandoori Half.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Chicken 65 Boneless",
      DishDescrip: "Chicken 65 Boneless",
      DishCost: "£14",
      URL: "./images/menuimg/023_Chicken 65 Boneless.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Chicken Lollypop / Saucy",
      DishDescrip: "Chicken Lollypop / Saucy",
      DishCost: "£15",
      URL: "./images/menuimg/024_Chicken Lollypop.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Dragan Chicken",
      DishDescrip: "Dragan Chicken",
      DishCost: "£10",
      URL: "./images/menuimg/025_Dragon Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Korean Fried Chicken",
      DishDescrip: "Korean Fried Chicken",
      DishCost: "£11",
      URL: "./images/menuimg/026_Korean Fried Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Fish Finger",
      DishDescrip: "Fish Finger",
      DishCost: "£12",
      URL: "./images/menuimg/027_Fish Finger.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Prawn 65",
      DishDescrip: "Prawn 65",
      DishCost: "£13",
      URL: "./images/menuimg/028_Prawn 65.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Mutton Chukka",
      DishDescrip: "Mutton Chukka",
      DishCost: "£14",
      URL: "./images/menuimg/029_Mutton Chukka.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Chicken Nuggets",
      DishDescrip: "Chicken Nuggets",
      DishCost: "£15",
      URL: "./images/menuimg/030_Chicken Nuggets.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Sweet Chilli Chicken",
      DishDescrip: "Sweet Chilli Chicken",
      DishCost: "£10",
      URL: "./images/menuimg/031_Sweet Chilli Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "Neththali",
      DishDescrip: "Neththali",
      DishCost: "£11",
      URL: "./images/menuimg/032_Netholi Meen.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Starters",
      SubCategory: "Non Veg Starters",
      DishName: "King Fish",
      DishDescrip: "King Fish",
      DishCost: "£12",
      URL: "./images/menuimg/033_King Fish Fry.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Biriyani",
      DishName: "Chicken Biriyani",
      DishDescrip: "Chicken Biriyani",
      DishCost: "£13",
      URL: "./images/menuimg/034_Chicken Biriyani.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Biriyani",
      DishName: "Lamb Biriyani",
      DishDescrip: "Lamb Biriyani",
      DishCost: "£14",
      URL: "./images/menuimg/035_Lamb Biriyani.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Biriyani",
      DishName: "Veg Biriyani",
      DishDescrip: "Veg Biriyani",
      DishCost: "£15",
      URL: "./images/menuimg/036_Veg Biriyani.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Biriyani",
      DishName: "Chicken 65 Biriyani",
      DishDescrip: "Chicken 65 Biriyani",
      DishCost: "£10",
      URL: "./images/menuimg/037_Chicken 65 Biriyani.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Biriyani",
      DishName: "Prawn Biryani",
      DishDescrip: "Prawn Biryani",
      DishCost: "£11",
      URL: "./images/menuimg/038_Prawn Biryani.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Biriyani",
      DishName: "Egg Biriyani",
      DishDescrip: "Egg Biriyani",
      DishCost: "£12",
      URL: "./images/menuimg/039_Egg Biriyani.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Gravy",
      DishName: "Panner Butter Masala",
      DishDescrip: "Panner Butter Masala",
      DishCost: "£13",
      URL: "./images/menuimg/040_Panner Butter Masala.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Gravy",
      DishName: "Panner Manjurian",
      DishDescrip: "Panner Manjurian",
      DishCost: "£14",
      URL: "./images/menuimg/041_Paneer manchurian.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Gravy",
      DishName: "Chilli Panner",
      DishDescrip: "Chilli Panner",
      DishCost: "£15",
      URL: "./images/menuimg/042_Chilli Panner.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Gravy",
      DishName: "Mshroom Masala",
      DishDescrip: "Mshroom Masala",
      DishCost: "£10",
      URL: "./images/menuimg/043_Mushroom Masala.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Gravy",
      DishName: "Chilli Mushroom",
      DishDescrip: "Chilli Mushroom",
      DishCost: "£11",
      URL: "./images/menuimg/044_Chilli Mushroom.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Gravy",
      DishName: "Gobi Masala",
      DishDescrip: "Gobi Masala",
      DishCost: "£12",
      URL: "./images/menuimg/045_Gobi Masala.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Gravy",
      DishName: "Chilli Gobi",
      DishDescrip: "Chilli Gobi",
      DishCost: "£13",
      URL: "./images/menuimg/046_Chilli Gobi.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Gravy",
      DishName: "Dahl Curry",
      DishDescrip: "Dahl Curry",
      DishCost: "£14",
      URL: "./images/menuimg/047_Dahl Curry.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Chettinadu Chicken Gravy",
      DishDescrip: "Chettinadu Chicken Gravy",
      DishCost: "£15",
      URL: "./images/menuimg/048_Chettinad Chicken Gravy.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Chettinadu Lamb Gravy",
      DishDescrip: "Chettinadu Lamb Gravy",
      DishCost: "£10",
      URL: "./images/menuimg/049_Chettinadu Lamb Gravy.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Chicken Manjurian",
      DishDescrip: "Chicken Manjurian",
      DishCost: "£11",
      URL: "./images/menuimg/050_Chicken manchurian gravy.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Chilli Chicken",
      DishDescrip: "Chilli Chicken",
      DishCost: "£12",
      URL: "./images/menuimg/051_Chilli Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Ginger Chicken",
      DishDescrip: "Ginger Chicken",
      DishCost: "£13",
      URL: "./images/menuimg/052_Ginger Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Garlic Chicken",
      DishDescrip: "Garlic Chicken",
      DishCost: "£14",
      URL: "./images/menuimg/053_Garlic Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Pepper Chicken",
      DishDescrip: "Pepper Chicken",
      DishCost: "£15",
      URL: "./images/menuimg/054_Pepper Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Kadai Chicken",
      DishDescrip: "Kadai Chicken",
      DishCost: "£10",
      URL: "./images/menuimg/055_Kadai Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Butter Chicken",
      DishDescrip: "Butter Chicken",
      DishCost: "£11",
      URL: "./images/menuimg/056_Butter Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Mutton Masala",
      DishDescrip: "Mutton Masala",
      DishCost: "£12",
      URL: "./images/menuimg/057_Mutton Masala.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Prawn Masala",
      DishDescrip: "Prawn Masala",
      DishCost: "£13",
      URL: "./images/menuimg/058_Prawn Masala.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Prawn Thokku",
      DishDescrip: "Prawn Thokku",
      DishCost: "£14",
      URL: "./images/menuimg/059_Prawn Thokku.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Hyderabad Chicken",
      DishDescrip: "Hyderabad Chicken",
      DishCost: "£15",
      URL: "./images/menuimg/060_Hyderabad Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Punjabi Chicken",
      DishDescrip: "Punjabi Chicken",
      DishCost: "£10",
      URL: "./images/menuimg/061_Punjabi Chicken.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Fish Gravy",
      DishDescrip: "Fish Gravy",
      DishCost: "£11",
      URL: "./images/menuimg/062_Fish Gravy.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Thalcha",
      DishDescrip: "Thalcha",
      DishCost: "£12",
      URL: "./images/menuimg/063_Dalcha.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Lamb Gravy",
      DishDescrip: "Lamb Gravy",
      DishCost: "£13",
      URL: "./images/menuimg/064_Lamb Gravy.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Gravy",
      DishName: "Chicken Gravy",
      DishDescrip: "Chicken Gravy",
      DishCost: "£14",
      URL: "./images/menuimg/065_Chicken Gravy.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Fried Rice",
      DishName: "Malaysian Chicken Fried Rice",
      DishDescrip: "Malaysian Chicken Fried Rice",
      DishCost: "£15",
      URL: "./images/menuimg/065_Chicken Gravy.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Fried Rice",
      DishName: "Chicken Fried Rice",
      DishDescrip: "Chicken Fried Rice",
      DishCost: "£10",
      URL: "./images/menuimg/066_Malaysian Chicken Fried Rice.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Fried Rice",
      DishName: "Chicken Fried Rice Schezwan",
      DishDescrip: "Chicken Fried Rice Schezwan",
      DishCost: "£11",
      URL: "./images/menuimg/067_Chicken Fried Rice.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Fried Rice",
      DishName: "Prawn Fried Rice",
      DishDescrip: "Prawn Fried Rice",
      DishCost: "£12",
      URL: "./images/menuimg/068_Chicken Fried Rice Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Fried Rice",
      DishName: "Prawn Fried Rice Schezwan",
      DishDescrip: "Prawn Fried Rice Schezwan",
      DishCost: "£13",
      URL: "./images/menuimg/069_Prawn Fried Rice.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Fried Rice",
      DishName: "Mixed Fried Rice",
      DishDescrip: "Mixed Fried Rice",
      DishCost: "£14",
      URL: "./images/menuimg/070_Prawn Fried Rice Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Fried Rice",
      DishName: "Mixed Fried Rice Schezwan",
      DishDescrip: "Mixed Fried Rice Schezwan",
      DishCost: "£15",
      URL: "./images/menuimg/071_Mixed Fried Rice.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Fried Rice",
      DishName: "Egg Fried Rice",
      DishDescrip: "Egg Fried Rice",
      DishCost: "£10",
      URL: "./images/menuimg/072_Mixed Fried Rice Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Fried Rice",
      DishName: "Egg Fried Rice Schezwan",
      DishDescrip: "Egg Fried Rice Schezwan",
      DishCost: "£11",
      URL: "./images/menuimg/073_Egg Fried Rice.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Noodles",
      DishName: "Malaysian Chicken Noodles",
      DishDescrip: "Malaysian Chicken Noodles",
      DishCost: "£12",
      URL: "./images/menuimg/074_Malaysian Chicken Noodles.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Noodles",
      DishName: "Chicken Noodles",
      DishDescrip: "Chicken Noodles",
      DishCost: "£13",
      URL: "./images/menuimg/075_Chicken Noodles.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Noodles",
      DishName: "Chicken Noodles Schezwan",
      DishDescrip: "Chicken Noodles Schezwan",
      DishCost: "£14",
      URL: "./images/menuimg/076_Chicken Noodles Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Noodles",
      DishName: "Prawn Noodles",
      DishDescrip: "Prawn Noodles",
      DishCost: "£15",
      URL: "./images/menuimg/077_Prawn Noodles.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Noodles",
      DishName: "Prawn Noodles Schezwan",
      DishDescrip: "Prawn Noodles Schezwan",
      DishCost: "£10",
      URL: "./images/menuimg/078_Prawn Noodles Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Noodles",
      DishName: "Mixed Noodles",
      DishDescrip: "Mixed Noodles",
      DishCost: "£11",
      URL: "./images/menuimg/079_Mixed Noodles.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Noodles",
      DishName: "Mixed Noodles Schezwan",
      DishDescrip: "Mixed Noodles Schezwan",
      DishCost: "£12",
      URL: "./images/menuimg/080_Mixed Noodles Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Noodles",
      DishName: "Egg Noodles",
      DishDescrip: "Egg Noodles",
      DishCost: "£13",
      URL: "./images/menuimg/081_Egg Noodles.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Noodles",
      DishName: "Egg Noodles Schezwan",
      DishDescrip: "Egg Noodles Schezwan",
      DishCost: "£14",
      URL: "./images/menuimg/082_Egg Noodles Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Fried Rice",
      DishName: "Veg Fried Rice",
      DishDescrip: "Veg Fried Rice",
      DishCost: "£15",
      URL: "./images/menuimg/083_Veg Fried Rice.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Fried Rice",
      DishName: "Veg Fried Rice Schezwan",
      DishDescrip: "Veg Fried Rice Schezwan",
      DishCost: "£10",
      URL: "./images/menuimg/084_Veg Fried Rice Schezwan.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Fried Rice",
      DishName: "Panner Fried Rice",
      DishDescrip: "Panner Fried Rice",
      DishCost: "£11",
      URL: "./images/menuimg/085_Panner Fried Rice.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Fried Rice",
      DishName: "Panner Fried Rice Schezwan",
      DishDescrip: "Panner Fried Rice Schezwan",
      DishCost: "£12",
      URL: "./images/menuimg/086_Panner Fried Rice Schezwan.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Fried Rice",
      DishName: "Mushroom Fried Rice",
      DishDescrip: "Mushroom Fried Rice",
      DishCost: "£13",
      URL: "./images/menuimg/087_Mushroom Fried Rice.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Fried Rice",
      DishName: "Mushroom Fried Rice Schezwan",
      DishDescrip: "Mushroom Fried Rice Schezwan",
      DishCost: "£14",
      URL: "./images/menuimg/088_Mushroom Fried Rice Schezwan.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Fried Rice",
      DishName: "Gobi Fried Rice",
      DishDescrip: "Gobi Fried Rice",
      DishCost: "£15",
      URL: "./images/menuimg/089_Gobi Fried Rice.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Fried Rice",
      DishName: "Gobi Fried Rice Schezwan",
      DishDescrip: "Gobi Fried Rice Schezwan",
      DishCost: "£10",
      URL: "./images/menuimg/090_ Gobi Fried Rice Schezwan.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Fried Rice",
      DishName: "Veg Mix Fried Rice",
      DishDescrip: "Veg Mix Fried Rice",
      DishCost: "£11",
      URL: "./images/menuimg/091_Veg Mix Fried Rice.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Fried Rice",
      DishName: "Veg Mix Fried Rice Schezwan",
      DishDescrip: "Veg Mix Fried Rice Schezwan",
      DishCost: "£12",
      URL: "./images/menuimg/092_Veg Mix Fried Rice Schezwan.png",
      isVeg: true,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Noodles",
      DishName: "Veg Fried Noodles",
      DishDescrip: "Veg Fried Noodles",
      DishCost: "£13",
      URL: "./images/menuimg/093_Veg Fried Noodles.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Noodles",
      DishName: "Veg Fried Noodles Schezwan",
      DishDescrip: "Veg Fried Noodles Schezwan",
      DishCost: "£14",
      URL: "./images/menuimg/094_ Veg Fried Noodles Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Noodles",
      DishName: "Panner Noodles",
      DishDescrip: "Panner Noodles",
      DishCost: "£15",
      URL: "./images/menuimg/095_Paneer Noodles.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Noodles",
      DishName: "Panner Noodles Schezwan",
      DishDescrip: "Panner Noodles Schezwan",
      DishCost: "£10",
      URL: "./images/menuimg/096_Paneer Noodles Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Noodles",
      DishName: "Mushroom Noodles",
      DishDescrip: "Mushroom Noodles",
      DishCost: "£11",
      URL: "./images/menuimg/097_Mushroom Noodles.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Noodles",
      DishName: "Mushroom Noodles Schezwan",
      DishDescrip: "Mushroom Noodles Schezwan",
      DishCost: "£12",
      URL: "./images/menuimg/098_Mushroom Noodles Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Noodles",
      DishName: "Gobi Noodles",
      DishDescrip: "Gobi Noodles",
      DishCost: "£13",
      URL: "./images/menuimg/099_Gobi Noodles.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Noodles",
      DishName: "Gobi Noodles Schezwan",
      DishDescrip: "Gobi Noodles Schezwan",
      DishCost: "£14",
      URL: "./images/menuimg/100_Gobi Noodles Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Noodles",
      DishName: "Veg Mix Noodles",
      DishDescrip: "Veg Mix Noodles",
      DishCost: "£15",
      URL: "./images/menuimg/101_Veg Mix Noodles.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Noodles",
      DishName: "Veg Mix Noodles Schezwan",
      DishDescrip: "Veg Mix Noodles Schezwan",
      DishCost: "£10",
      URL: "./images/menuimg/102_Veg Mix Noodles Schezwan.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Dosa",
      DishName: "Ghee Roast",
      DishDescrip: "Ghee Roast",
      DishCost: "£11",
      URL: "./images/menuimg/103_Ghee Roast.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Dosa",
      DishName: "Paper Roast",
      DishDescrip: "Paper Roast",
      DishCost: "£12",
      URL: "./images/menuimg/104_Paper Roast.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Dosa",
      DishName: "Egg Dosai",
      DishDescrip: "Egg Dosai",
      DishCost: "£13",
      URL: "./images/menuimg/105_Egg Dosai.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Dosa",
      DishName: "Kal Dosai (set) / Utthapam",
      DishDescrip: "Kal Dosai (set) / Utthapam",
      DishCost: "£14",
      URL: "./images/menuimg/106_Kal Dosai.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Dosa",
      DishName: "Masala Dosai",
      DishDescrip: "Masala Dosai",
      DishCost: "£15",
      URL: "./images/menuimg/107_Masala Dosai.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Dosa",
      DishName: "Chicken Kari Dosai",
      DishDescrip: "Chicken Kari Dosai",
      DishCost: "£10",
      URL: "./images/menuimg/108_Chicken Kari Dosai.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Dosa",
      DishName: "Mutton Kari Dosai",
      DishDescrip: "Mutton Kari Dosai",
      DishCost: "£11",
      URL: "./images/menuimg/109_Mutton Kari Dosai.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Dosa",
      DishName: "Plain Dosa",
      DishDescrip: "Plain Dosa",
      DishCost: "£12",
      URL: "./images/menuimg/110_Plain Dosa.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Tiffen Items",
      DishName: "Idly",
      DishDescrip: "Idly",
      DishCost: "£13",
      URL: "./images/menuimg/111_Idly.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Tiffen Items",
      DishName: "Poori with Masala",
      DishDescrip: "Poori with Masala",
      DishCost: "£14",
      URL: "./images/menuimg/112_Poori with Masala.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Prawn Parotta",
      DishDescrip: "Prawn Parotta",
      DishCost: "£15",
      URL: "./images/menuimg/113_Prawn Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Ceylon Parotta",
      DishDescrip: "Ceylon Parotta",
      DishCost: "£10",
      URL: "./images/menuimg/114_Ceylon Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Chicken Parotta",
      DishDescrip: "Chicken Parotta",
      DishCost: "£11",
      URL: "./images/menuimg/115_Chicken Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Mutton/Lamba Parotta",
      DishDescrip: "Mutton/Lamba Parotta",
      DishCost: "£12",
      URL: "./images/menuimg/116_Mutton Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Murtaba Chicken Parotta",
      DishDescrip: "Murtaba Chicken Parotta",
      DishCost: "£13",
      URL: "./images/menuimg/117_ Murtaba Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Chicken Kothu Parotta",
      DishDescrip: "Chicken Kothu Parotta",
      DishCost: "£14",
      URL: "./images/menuimg/119_Chicken Kothu Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Egg Kothu Parotta",
      DishDescrip: "Egg Kothu Parotta",
      DishCost: "£15",
      URL: "./images/menuimg/120_Egg Kothu Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Lamb Kothu Parotta",
      DishDescrip: "Lamb Kothu Parotta",
      DishCost: "£10",
      URL: "./images/menuimg/121_Mutton Kothu Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Egg Onion Chilli Parotta",
      DishDescrip: "Egg Onion Chilli Parotta",
      DishCost: "£11",
      URL: "./images/menuimg/122_Egg Onion Chilli Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Plain Veechu Parotta",
      DishDescrip: "Plain Veechu Parotta",
      DishCost: "£12",
      URL: "./images/menuimg/123_Plain Veechu Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Egg Veechu Parotta",
      DishDescrip: "Egg Veechu Parotta",
      DishCost: "£13",
      URL: "./images/menuimg/124_Egg Veechu Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Plain Parotta (2Pcs)",
      DishDescrip: "Plain Parotta (2Pcs)",
      DishCost: "£14",
      URL: "./images/menuimg/125_Plain Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Non Veg Stuffed Parotta",
      DishName: "Seafood Kothu Parotta",
      DishDescrip: "Seafood Kothu Parotta",
      DishCost: "£15",
      URL: "./images/menuimg/126_Seafood Kothu Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Veg Mixed Parotta",
      DishDescrip: "Veg Mixed Parotta",
      DishCost: "£10",
      URL: "./images/menuimg/127_Veg Mixed Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Panner Parotta",
      DishDescrip: "Panner Parotta",
      DishCost: "£11",
      URL: "./images/menuimg/128_Panner Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Mushroom Parotta",
      DishDescrip: "Mushroom Parotta",
      DishCost: "£12",
      URL: "./images/menuimg/129_Mushroom Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Gobi Parotta",
      DishDescrip: "Gobi Parotta",
      DishCost: "£13",
      URL: "./images/menuimg/129_Mushroom Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Chilly Parotta",
      DishDescrip: "Chilly Parotta",
      DishCost: "£14",
      URL: "./images/menuimg/130_Chilly Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Cheese Parotta",
      DishDescrip: "Cheese Parotta",
      DishCost: "£15",
      URL: "./images/menuimg/131_Cheese Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Wheat Parotta",
      DishDescrip: "Wheat Parotta",
      DishCost: "£10",
      URL: "./images/menuimg/132_Wheat Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Chappathi",
      DishDescrip: "Chappathi",
      DishCost: "£11",
      URL: "./images/menuimg/133_Chappathi.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Banana Parotta",
      DishDescrip: "Banana Parotta",
      DishCost: "£12",
      URL: "./images/menuimg/134_Banana Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Chocolate Parotta",
      DishDescrip: "Chocolate Parotta",
      DishCost: "£13",
      URL: "./images/menuimg/135_ Chocolate Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Bun Parotta",
      DishDescrip: "Bun Parotta",
      DishCost: "£14",
      URL: "./images/menuimg/136_ Bun Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Crispy Parotta (Porucha) ",
      DishDescrip: "Crispy Parotta (Porucha) ",
      DishCost: "£15",
      URL: "./images/menuimg/137_Crispy Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "MainCourse",
      SubCategory: "Veg Stuffed Parotta",
      DishName: "Aloo Parotta",
      DishDescrip: "Aloo Parotta",
      DishCost: "£10",
      URL: "./images/menuimg/138_Aloo Parotta.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Sides",
      SubCategory: "Rice",
      DishName: "Plain Rice",
      DishDescrip: "Plain Rice",
      DishCost: "£11",
      URL: "./images/menuimg/139_Plain Rice.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Sides",
      SubCategory: "Rice",
      DishName: "Ghee Rice",
      DishDescrip: "Ghee Rice",
      DishCost: "£12",
      URL: "./images/menuimg/140_Ghee Rice.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Sides",
      SubCategory: "Rice",
      DishName: "Cocunut Milk Rice",
      DishDescrip: "Cocunut Milk Rice",
      DishCost: "£13",
      URL: "./images/menuimg/141_Coconut Milk Rice.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Sides",
      SubCategory: "Egg Special",
      DishName: "Omlet",
      DishDescrip: "Omlet",
      DishCost: "£14",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Sides",
      SubCategory: "Egg Special",
      DishName: "Kalaki",
      DishDescrip: "Kalaki",
      DishCost: "£15",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Sides",
      SubCategory: "Egg Special",
      DishName: "Egg Podi Mass",
      DishDescrip: "Egg Podi Mass",
      DishCost: "£13",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Sides",
      SubCategory: "Egg Special",
      DishName: "Masala Omlet",
      DishDescrip: "Masala Omlet",
      DishCost: "£14",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Sides",
      SubCategory: "Egg Special",
      DishName: "Egg Masala",
      DishDescrip: "Egg Masala",
      DishCost: "£15",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: false,
      spicelevel: 1,
    },
    {
      Category: "Sides",
      SubCategory: "Salads",
      DishName: "Raita",
      DishDescrip: "Raita",
      DishCost: "£10",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Sides",
      SubCategory: "Salads",
      DishName: "Kathika Katta/Thoku",
      DishDescrip: "Kathika Katta/Thoku",
      DishCost: "£11",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Sides",
      SubCategory: "Naan",
      DishName: "Plain Naan",
      DishDescrip: "Plain Naan",
      DishCost: "£12",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Sides",
      SubCategory: "Naan",
      DishName: "Garlic Naan",
      DishDescrip: "Garlic Naan",
      DishCost: "£13",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Drinks",
      SubCategory: "Hot Drinks",
      DishName: "Plain Tea (Black Tea)",
      DishDescrip: "Plain Tea (Black Tea)",
      DishCost: "£14",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Drinks",
      SubCategory: "Hot Drinks",
      DishName: "Tea with Milk (English)",
      DishDescrip: "Tea with Milk (English)",
      DishCost: "£15",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Drinks",
      SubCategory: "Hot Drinks",
      DishName: "Masala Tea (Indian)",
      DishDescrip: "Masala Tea (Indian)",
      DishCost: "£13",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Drinks",
      SubCategory: "Hot Drinks",
      DishName: "Coffee",
      DishDescrip: "Coffee",
      DishCost: "£14",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Drinks",
      SubCategory: "Soft Drinks",
      DishName: "Coke",
      DishDescrip: "Coke",
      DishCost: "£15",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Drinks",
      SubCategory: "Soft Drinks",
      DishName: "Pepsi",
      DishDescrip: "Pepsi",
      DishCost: "£10",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Drinks",
      SubCategory: "Soft Drinks",
      DishName: "Fanta",
      DishDescrip: "Fanta",
      DishCost: "£11",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Drinks",
      SubCategory: "Soft Drinks",
      DishName: "7up",
      DishDescrip: "7up",
      DishCost: "£12",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Drinks",
      SubCategory: "Soft Drinks",
      DishName: "Diet Coke",
      DishDescrip: "Diet Coke",
      DishCost: "£13",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
    {
      Category: "Drinks",
      SubCategory: "Soft Drinks",
      DishName: "Diet Pepsi",
      DishDescrip: "Diet Pepsi",
      DishCost: "£14",
      URL: "./images/menuimg/001_ChickenRoll.png",
      isVeg: true,
      spicelevel: 0,
    },
  ],
};
